#!/bin/bash

cd ..
git clone --recursive https://github.com/cyckun/libOTe.git
cd libOTe
unzip libOTe.zip -d .
cd cryptoTools
cd thirdparty/linux
bash all.get
cd ../../..
cmake -D ENABLE_MIRACL=ON .
make
cd ../OPRF-PSI
cmake .
make

